schema-version = 1
release-version = "1.27.1"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[sdk]
name = "bottlerocket-sdk"
version = "0.47.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "4.0.0"
vendor = "bottlerocket"
